### ISSUE TITLE
Turn on CI

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/epanet-python#30]
I need an administrator to turn on Appveyor for this repo. Thanks!

**Comment by samhatchett** [comment]
@michaeltryby could you lead this horse to water please? how do I turn on appveyer?

**Comment by michaeltryby** [comment]
I think you need to log into OWA Appveyor account and then create a project for the epanet-python repo.

**Comment by samhatchett** [comment]
sorry - is this not resolved?

**Comment by michaeltryby** [comment]
@samhatchett Yeah, I need Appveyor configured for the dev branch. Right now it's looking at master.

**Comment by michaeltryby** [comment]
@samhatchett Thanks! I really appreciate it.
