### ISSUE TITLE
API to access headloss model code

### ISSUE THREAD

**Issue by jbaayen** [OpenWaterAnalytics/epanet-python#43]
Currently, there appears to be no way to access the headloss model code using the API. Such API would be useful to help correctly interpret the roughness values after having read an input file.

**Comment by michaeltryby** [comment]
@jbaayen ```anlys_getoption(handle, en.Option.HEADLOSSFORM)``` - returns the headloss formula being used as an integer. 

I have not figured out how to have the SWIG wrapper return an Enum in Python. Any suggestions?
