### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/epanet-python#45]
I'm working on a dockerized build for this wrapper - feel free to use if it suits your needs!

https://gist.github.com/samhatchett/f13b098e7ae0cc092e06cc17a4828fc3

**Comment by michaeltryby** [comment]
@samhatchett 😎

**Comment by michaeltryby** [comment]
@samhatchett Now that Appveyor supports Linux I was thinking of adding it to the build matrix. That way I can generate wheels for Linux using the CI worker. 

Is that something you would find helpful?

**Comment by samhatchett** [comment]
sure, I'm still quite ignorant of wheels vs other methods of distribution unfortunately. what would be really useful is a pip-installable swig-wrapped epanet - although I'm not sure how pip does with high-churn package distribution or CI... but in any case I think the answer is yes!

**Comment by pshassett** [comment]
I would use Linux wheels for applying epanet-python in WNTR.

**Comment by michaeltryby** [comment]
Appveyor supports Linux build workers so we should be able to add it to the existing setup.
