### ISSUE TITLE
Negative pressures warning with net6 

### ISSUE THREAD

**Issue by pshassett** [OpenWaterAnalytics/epanet-python#48]
I am getting the Exception: WARNING: System has negative pressures. while running
 `from epanet.toolkit import toolkit as EN
inpfile = 'Networks/Net6.inp'
rptfile = 'temp.rpt'
binfile = 'temp.bin'

errors = []

ph = EN.proj_create()
errors.append(EN.proj_open(ph, inpfile, rptfile, binfile))
errors.append(EN.hydr_solve(ph))` 

This inconsistent with EPANET2 behavior with the same .inp file

**Comment by samhatchett** [comment]
could you please post/link the `Net6.inp` file so that somebody can reproduce? 

Also, are you saying that the simulation does not produce negative pressures under EPANET2, or that EPANET2 does not give an exception when producing negative pressures?

thanks for reporting!

**Comment by pshassett** [comment]
Hi @samhatchett, thanks for responding!  [Here is the inp file](https://github.com/OpenWaterAnalytics/WNTR/blob/master/examples/networks/Net6.inp).  

In EPANET2 "Warning: PUMP-3867 open but exceeds maximum flow at 51:44:28 hrs." is produced and comes up again at 76:23:27 and 88:52:22.  This could be a difference in how extreme demands are being handled between the two versions.  It would be interesting to see how it behaves under PDA demand model.

**Comment by samhatchett** [comment]
@michaeltryby - it looks like this is a case where 2.2-dev may differ from 2.00.12. 

not sure how to address - should we add to the regression tests?

**Comment by pshassett** [comment]
Running with `errors.append(EN.dmnd_setmodel(ph,1,pmin,preq,pexp))` produces "WARNING: Pumps cannot deliver enough flow or head."  
It would be nice to know which pump was exceeding flowrate...

**Comment by michaeltryby** [comment]
@pshassett Thanks for creating this issue. Could you tell me, what version of `epanet-python` are you running -- 32-bit or 64-bit windows? Thanks!

**Comment by michaeltryby** [comment]
@samhatchett Yeah I agree, this looks like a good candidate for the reg tests. I will take a closer look and let you and @pshassett know what I discover.

**Comment by pshassett** [comment]
Hey Sam.  I'm running on 64 bit windows with python 3.7.  Thanks for looking into it Michael.

**Comment by dly9000** [comment]
I am getting the same issue with any Warning flag raised when running en.hyd_solve(ph) throwing an Exception and stopping my code from progressing.

```
import epanet.toolkit.toolkit as en
inpfile = "toy_PDA.inp"
toy = en.proj_create()
en.proj_open(toy,inpfile,"report.rpt","")
en.hydr_solve(tg)
```

```
Traceback (most recent call last):
  File "path\epanetSwigTester.py", line 8, in <module>
    errors.append(en.hydr_solve(tg))
  File "C:\Python36\lib\site-packages\epanet\toolkit\toolkit.py", line 367, in hydr_solve
    return _toolkit.hydr_solve(ph)
Exception: WARNING: Valves cannot deliver enough flow.
```
[toy_PDA.txt](https://github.com/OpenWaterAnalytics/epanet-python/files/3000838/toy_PDA.txt)

I am running Python 3.6 64 bit.

**Comment by michaeltryby** [comment]
@dly9000 you are referring to a known issue that has already been fixed. See #46. I will update the release with the new wheels ASAP.

**Comment by dly9000** [comment]
@michaeltryby you are correct.  It did not occur to me to look in the closed isuses.  Thank you for all your work!

**Comment by pshassett** [comment]
I think this is more of an issue with the Network Model and not necessarily an issue with epanet-python.
