### ISSUE TITLE
dmnd_setmodel() type argument is integer

### ISSUE THREAD

**Issue by pshassett** [OpenWaterAnalytics/epanet-python#51]
`dmnd_setmodel(ph: 'Handle', type: 'int', pmin: 'double', preq: 'double', pexp: 'double') -> "int":`

To match the rest of the toolkit wrapper, shouldn't the type of `type` be EN.DemandModel enum?  

Calling `EN.dmnd_setmodel(ph, EN.DemandModel.PDA, pmin, preq, pexp)` raises 
'TypeError: in method 'dmnd_setmodel', argument 2 of type 'int'' in spyder.

**Comment by samhatchett** [comment]
I'm grooming the backlog here - I think this issue relates to the swig-wrapped package devised by Tryby - so unless he wants to offer support on it, I'll suggest closing.

**Comment by pshassett** [comment]
It is in regard to the epanet_python module. This was a more nuanced inconsistency, I think it can be closed for the time being.
