### ISSUE TITLE
Water quality analysis error

### ISSUE THREAD

**Issue by GalPerelman** [OpenWaterAnalytics/epanet-python#52]
Hi,
When calling quality analysis functions such as EN.initQ() or EN.runQ() I get the following error:

```
File "path_to_epamodule.py/epamodule.py", line 624, in ENinitQ
if ierr !=0: raise ENtoolkitError(ierr)
epamodule.ENtoolkitError: Error 105: water quality solver not opened
```

I'm using Python 3.7 on windows 64 bit

**Comment by samhatchett** [comment]
Thanks for reporting. To avoid confusion, I've labelled this for the sub-project it applies to. 

You could also try the pip-installable `owa-epanet` package and see if that one works for you.

**Comment by GalPerelman** [comment]
Hi Sam
Just realized what was my problem
I misunderstood the right way to use these functions

Thank you for the quick response

**Comment by samhatchett** [comment]
great, feel free to close the issue if you feel that this is resolved. best of luck!
