### ISSUE TITLE
Issue with ENsetoption() function

### ISSUE THREAD

**Issue by smnsierra** [OpenWaterAnalytics/epanet-python#6]
Hell everyone, I ran into an issue with the function in the object.
I guess at line [535](https://github.com/OpenWaterAnalytics/epanet-python/blob/b43690a473beaf1d4ffc581b119adf48b571eb46/epamodule.py#L535), it should be `optioncode` instead of `paramcode`.

**Comment by mauriziocingi** [comment]
Done.
