### ISSUE TITLE
Error in CMakeLists.txt - Ws7 & VS 2019

### ISSUE THREAD

**Issue by pajarrige** [OpenWaterAnalytics/epanet-python#62]
Trying to generate whl for py 3.8-32 (python 3.8.5) under Ws7 / VS2019, the chain fails to generate .whl.
The fix consists in removing the 'Release' path chunk from the last two copy commands from /bin/Release and /lib/Release
[CMakeLists.txt](https://github.com/OpenWaterAnalytics/epanet-python/files/5114854/CMakeLists.txt)

**Comment by samhatchett** [comment]
Thanks for the note - @sm-rana do you have any thoughts on this? I want to make sure this still works for Windows users.

**Comment by sm-rana** [comment]
> Trying to generate whl for py 3.8-32 (python 3.8.5) under Ws7 / VS2019, the chain fails to generate .whl.
> The fix consists in removing the 'Release' path chunk from the last two copy commands from /bin/Release and /lib/Release
> [CMakeLists.txt](https://github.com/OpenWaterAnalytics/epanet-python/files/5114854/CMakeLists.txt)


@samhatchett  I just tried compiling with VS 2017 (MSVC 14.16.27023) and I agree with @pajarrige the `Release` folder is not being created under `/bin` or `/lib` and getting rid of `Release` allowed it to compile successfully.

**Comment by samhatchett** [comment]
Thanks all - PRs are welcome!

**Comment by samhatchett** [comment]
Closing as fixed - thanks @samrensenhouse !
