### ISSUE TITLE
Some tips in the installation on windows 

### ISSUE THREAD

**Issue by LittleBrize** [OpenWaterAnalytics/epanet-python#70]
With several trials, i installed it successfully. Some tips may be useful for you, as listed below.
1) Before all the tips, you should know the epanet version run successfully only on the python 3.x. My python version is 3.7.9. 
2) it requires the python module "scikit-build". You can install them easily via command line "pip install scikit-build".
3) it requires the SWIG. Download the package from the official website and unzip it. Then add the path of file to system path.
4) Because the installation requires cmake to complie the C source codes, cmake certainly need to be installed on your platform.
5) Just follow the "README". Take the command line and build the libraries. Finally, you can use it through the updated file named by "epanet" under "packages".

**Comment by samhatchett** [comment]
closing as I have moved this very helpful list to a wiki: https://github.com/OpenWaterAnalytics/epanet-python/wiki/tips-for-building-on-windows
